window.SIX_SPIRITS_ABILITIES = [
  {
    "code": "S01",
    "type": "spade",
    "suit": "♠",
    "name": "관성 잠금",
    "en": "INERTIA LOCK",
    "effect": "손이 닿은 대상의 현재 운동량을 최대 3초간 고정한다.",
    "limit": "동시에 하나만 유지 가능하며, 멈춘 힘은 해제 순간 되돌아온다.",
    "burst": "관절이 굳고 과부하 시 자신의 몸까지 순간 정지한다.",
  },
  {
    "code": "S02",
    "type": "spade",
    "suit": "♠",
    "name": "반동 전가",
    "en": "RECOIL TRANSFER",
    "effect": "받아낸 충격 일부를 저장해 다음 타격이나 도약에 실어 보낸다.",
    "limit": "한 번에 하나만 저장하며 10초 안에 방출하지 않으면 자신이 받는다.",
    "burst": "멍과 미세 골절이 누적된다.",
  },
  {
    "code": "S03",
    "type": "spade",
    "suit": "♠",
    "name": "궤도 편향",
    "en": "TRAJECTORY BIAS",
    "effect": "시야 안에서 움직이는 물체의 방향을 완만하게 꺾는다.",
    "limit": "정지한 물체에는 쓸 수 없고 최대 편향은 약 15도다.",
    "burst": "평형감각이 무너지고 시야가 회전한다.",
  },
  {
    "code": "S04",
    "type": "spade",
    "suit": "♠",
    "name": "감각 압축",
    "en": "SENSE COMPRESSION",
    "effect": "최대 5초 동안 감각 처리 속도를 끌어올려 주변이 느려진 듯 인식한다.",
    "limit": "사고만 빨라질 뿐 신체 속도는 늘지 않는다.",
    "burst": "편두통, 코피, 기억 누락이 생긴다.",
  },
  {
    "code": "S05",
    "type": "spade",
    "suit": "♠",
    "name": "접지",
    "en": "DEAD ANCHOR",
    "effect": "자신의 유효 중량을 높여 충격과 밀쳐내기에 버틴다.",
    "limit": "출력이 높을수록 움직일 수 없고 약한 바닥에서는 그대로 꺼진다.",
    "burst": "무릎과 척추에 압력이 집중된다.",
  },
  {
    "code": "S06",
    "type": "spade",
    "suit": "♠",
    "name": "스텝 스킵",
    "en": "STEP SKIP",
    "effect": "발을 디딘 순간 3미터 이내를 초고속으로 주파한다.",
    "limit": "직선 경로와 착지 공간이 필요하며 장애물을 통과하지 못한다.",
    "burst": "종아리 근섬유가 찢어지고 다리가 풀린다.",
  },
  {
    "code": "S07",
    "type": "spade",
    "suit": "♠",
    "name": "맥박 추적",
    "en": "PULSE TRACE",
    "effect": "반경 12미터 내 생명체의 심박과 호흡을 벽 너머로 감지한다.",
    "limit": "군중 속에서는 신호가 겹치며 기계에는 통하지 않는다.",
    "burst": "이명과 부정맥이 나타난다.",
  },
  {
    "code": "S08",
    "type": "spade",
    "suit": "♠",
    "name": "균형 탈취",
    "en": "BALANCE THEFT",
    "effect": "접촉한 대상의 평형감각을 5초간 빼앗아 자신의 균형을 강화한다.",
    "limit": "한 번에 한 명에게만 적용된다.",
    "burst": "효과 종료 후 어지럼증이 한꺼번에 되돌아온다.",
  },
  {
    "code": "S09",
    "type": "spade",
    "suit": "♠",
    "name": "골격 채무",
    "en": "BONE DEBT",
    "effect": "짧은 시간 뼈와 관절을 단단하게 만들어 타격과 낙하를 견딘다.",
    "limit": "통증과 손상은 사라지지 않고 해제 뒤 드러난다.",
    "burst": "미세 골절이 누적된다.",
  },
  {
    "code": "S10",
    "type": "spade",
    "suit": "♠",
    "name": "동작 각인",
    "en": "MOTION IMPRINT",
    "effect": "직전에 수행한 신체 동작 하나를 다음 한 번 완벽하게 재현한다.",
    "limit": "방향과 힘까지 동일하며 상황이 달라도 수정할 수 없다.",
    "burst": "근육 경련과 관절 잠김이 발생한다.",
  },
  {
    "code": "S11",
    "type": "spade",
    "suit": "♠",
    "name": "압력 표식",
    "en": "PRESSURE MARK",
    "effect": "손끝으로 찍은 지점에 다음 물리 충격을 집중시킨다.",
    "limit": "표식은 하나만 유지되며 30초 후 사라진다.",
    "burst": "손가락 감각이 둔해지고 손톱 아래 출혈이 생긴다.",
  },
  {
    "code": "S12",
    "type": "spade",
    "suit": "♠",
    "name": "벡터 반전",
    "en": "BACKSTEP VECTOR",
    "effect": "자신이 움직이던 방향을 즉시 반대로 뒤집는다.",
    "limit": "6초에 한 번만 가능하며 공중에서는 이동 거리가 절반이다.",
    "burst": "목과 허리에 채찍질 손상이 쌓인다.",
  },
  {
    "code": "H01",
    "type": "heart",
    "suit": "♥",
    "name": "감정 잔향",
    "en": "AFFECT ECHO",
    "effect": "사람이나 물건에 남은 가장 강한 최근 감정을 감지한다.",
    "limit": "사건 내용이나 기억 자체는 읽지 못한다.",
    "burst": "남의 감정이 자신의 것처럼 남는다.",
  },
  {
    "code": "H02",
    "type": "heart",
    "suit": "♥",
    "name": "고요 주입",
    "en": "STILLWATER",
    "effect": "한 대상의 공포와 흥분을 낮춰 호흡과 판단을 안정시킨다.",
    "limit": "의욕과 분노도 함께 가라앉는다.",
    "burst": "사용자가 대신 불안과 심박 상승을 떠안는다.",
  },
  {
    "code": "H03",
    "type": "heart",
    "suit": "♥",
    "name": "거짓말 체온",
    "en": "LIE HEAT",
    "effect": "심박, 체온, 호흡의 불일치를 감지해 거짓말 가능성을 읽는다.",
    "limit": "진실 판별이 아니며 착각하는 사람에게는 빗나간다.",
    "burst": "모든 말을 의심하는 편집증이 생긴다.",
  },
  {
    "code": "H04",
    "type": "heart",
    "suit": "♥",
    "name": "기억 북마크",
    "en": "MEMORY BOOKMARK",
    "effect": "현재 순간을 표시해 훗날 선명하게 떠올리게 한다.",
    "limit": "한 사람당 세 개까지만 유지되며 기억 수정은 불가능하다.",
    "burst": "현재와 과거가 겹쳐 플래시백이 생긴다.",
  },
  {
    "code": "H05",
    "type": "heart",
    "suit": "♥",
    "name": "통증 분할",
    "en": "PAIN SPLIT",
    "effect": "접촉한 두 사람 사이에 통증 감각을 원하는 비율로 나눈다.",
    "limit": "상처 자체는 옮겨지지 않는다.",
    "burst": "연결 종료 후에도 유령통이 남는다.",
  },
  {
    "code": "H06",
    "type": "heart",
    "suit": "♥",
    "name": "주의 사각",
    "en": "BLIND SPOT",
    "effect": "작은 물건이나 짧은 행동을 주변이 중요하지 않은 것으로 흘려보게 한다.",
    "limit": "투명화가 아니며 카메라와 직접 수색에는 통하지 않는다.",
    "burst": "사용자도 중요한 단서를 놓치기 시작한다.",
  },
  {
    "code": "H07",
    "type": "heart",
    "suit": "♥",
    "name": "적의 노이즈",
    "en": "INTENT STATIC",
    "effect": "반경 8미터 안에서 자신을 해칠 의도가 커지는 순간을 감지한다.",
    "limit": "정확한 인물이나 공격 방법은 알 수 없다.",
    "burst": "편집증과 수면 장애가 심해진다.",
  },
  {
    "code": "H08",
    "type": "heart",
    "suit": "♥",
    "name": "꿈의 잔금",
    "en": "DREAM RESIDUE",
    "effect": "잠든 사람의 표면적인 꿈에 들어가 대화하거나 상징을 관찰한다.",
    "limit": "깊은 기억을 강제로 열 수 없고 현실의 몸은 무방비다.",
    "burst": "환각과 수면마비가 생긴다.",
  },
  {
    "code": "H09",
    "type": "heart",
    "suit": "♥",
    "name": "감정 역류",
    "en": "FEEDBACK HEART",
    "effect": "상대가 자신에게 쏟은 감정을 되돌려 보내 강도를 증폭한다.",
    "limit": "없는 감정은 만들 수 없고 사용자도 일부를 함께 느낀다.",
    "burst": "자신과 타인의 욕망을 구분하지 못한다.",
  },
  {
    "code": "H10",
    "type": "heart",
    "suit": "♥",
    "name": "생체 템포",
    "en": "BIO TEMPO",
    "effect": "가까운 아군의 호흡과 심박을 맞춰 쇼크와 패닉을 늦춘다.",
    "limit": "치료가 아니며 3미터를 벗어나면 끊긴다.",
    "burst": "사용자의 심장이 불규칙해진다.",
  },
  {
    "code": "H11",
    "type": "heart",
    "suit": "♥",
    "name": "호명 지연",
    "en": "NAME DELAY",
    "effect": "상대가 받아들이는 이름을 정확히 불러 잠깐 행동을 망설이게 한다.",
    "limit": "한 대상에게 연속으로 통하지 않으며 이름을 틀리면 실패한다.",
    "burst": "이름과 단어를 잊기 시작한다.",
  },
  {
    "code": "H12",
    "type": "heart",
    "suit": "♥",
    "name": "무감실",
    "en": "QUIET ROOM",
    "effect": "최대 2분간 자신의 공포, 죄책감, 공감을 차단한다.",
    "limit": "판단력이 좋아지는 것은 아니며 감정적 대가는 해제 후 돌아온다.",
    "burst": "감정 붕괴와 기억 공백이 발생한다.",
  },
  {
    "code": "D01",
    "type": "diamond",
    "suit": "♦",
    "name": "열선",
    "en": "HEATLINE",
    "effect": "손끝으로 표면에 선을 그으면 수초 뒤 그 경로가 급격히 가열된다.",
    "limit": "비생명체 표면에만 새길 수 있고 선이 끊기면 멈춘다.",
    "burst": "손과 팔에 화상과 탈수가 생긴다.",
  },
  {
    "code": "D02",
    "type": "diamond",
    "suit": "♦",
    "name": "전하 금고",
    "en": "CHARGE BANK",
    "effect": "주변의 약한 전기를 흡수해 전격이나 장비 충전에 사용한다.",
    "limit": "대형 전력망은 통제할 수 없고 저장량에 한계가 있다.",
    "burst": "근육 경련과 부정맥이 발생한다.",
  },
  {
    "code": "D03",
    "type": "diamond",
    "suit": "♦",
    "name": "냉각 채무",
    "en": "COLD DEBT",
    "effect": "대상에서 열을 빼앗아 빠르게 식히거나 작은 범위를 얼린다.",
    "limit": "빼앗은 열은 사용자 몸에 쌓인다.",
    "burst": "고열, 탈수, 장기 과열이 발생한다.",
  },
  {
    "code": "D04",
    "type": "diamond",
    "suit": "♦",
    "name": "섬광 잔고",
    "en": "FLASH RESERVE",
    "effect": "주변 빛을 흡수해 저장했다가 눈부신 섬광으로 방출한다.",
    "limit": "어두운 곳에서는 충전이 느리다.",
    "burst": "망막 손상과 일시적 색맹이 나타난다.",
  },
  {
    "code": "D05",
    "type": "diamond",
    "suit": "♦",
    "name": "진동 점화",
    "en": "RESONANCE KICK",
    "effect": "접촉한 작은 물체에 진동을 누적해 균열과 파손을 일으킨다.",
    "limit": "재질을 파악하고 수초간 접촉해야 한다.",
    "burst": "내이 손상과 뼈의 미세 진동이 쌓인다.",
  },
  {
    "code": "D06",
    "type": "diamond",
    "suit": "♦",
    "name": "압축파",
    "en": "COMPRESSION POP",
    "effect": "손바닥 앞 공기를 순간 압축해 근거리 충격파를 만든다.",
    "limit": "사거리 6미터를 넘으면 급격히 약해진다.",
    "burst": "폐와 고막에 압력이 쌓인다.",
  },
  {
    "code": "D07",
    "type": "diamond",
    "suit": "♦",
    "name": "마찰 절단",
    "en": "FRICTION CUT",
    "effect": "작은 표면의 마찰을 크게 줄이거나 높인다.",
    "limit": "2제곱미터 이내에서 8초만 유지된다.",
    "burst": "손바닥 피부가 벗겨지고 관절이 과열된다.",
  },
  {
    "code": "D08",
    "type": "diamond",
    "suit": "♦",
    "name": "화상 인쇄",
    "en": "BURNPRINT",
    "effect": "비생명체에 보이지 않는 열 표식을 남겨 지연 발열시킨다.",
    "limit": "최대 세 개, 1분 이내, 20미터 안에서만 작동한다.",
    "burst": "표식 수만큼 사용자 피부에도 화상이 생긴다.",
  },
  {
    "code": "D09",
    "type": "diamond",
    "suit": "♦",
    "name": "방전 누수",
    "en": "NULL BATTERY",
    "effect": "접촉한 전자기기나 배터리의 에너지를 빠르게 소모시킨다.",
    "limit": "생체 에너지에는 통하지 않는다.",
    "burst": "손끝 신경이 마비되고 주변 기기가 오작동한다.",
  },
  {
    "code": "D10",
    "type": "diamond",
    "suit": "♦",
    "name": "전도 경로",
    "en": "CONDUCTION PATH",
    "effect": "두 금속 물체 사이로 열이나 전류가 우선 이동하게 만든다.",
    "limit": "두 대상은 15미터 이내에 있어야 한다.",
    "burst": "몸이 임시 도선처럼 반응해 신경통과 화상이 생긴다.",
  },
  {
    "code": "D11",
    "type": "diamond",
    "suit": "♦",
    "name": "점화 임계",
    "en": "LOWER THE MATCH",
    "effect": "비생명체 한 대상의 발화점이나 반응 임계치를 낮춘다.",
    "limit": "스스로 불을 만들지는 못한다.",
    "burst": "체온 조절이 망가져 오한과 고열이 반복된다.",
  },
  {
    "code": "D12",
    "type": "diamond",
    "suit": "♦",
    "name": "잔열 장막",
    "en": "AFTERHEAT VEIL",
    "effect": "받은 충격 일부를 열로 바꿔 몸 주변에 짧은 고열 장막을 만든다.",
    "limit": "관통 피해에는 약하고 주변 아군도 열의 영향을 받는다.",
    "burst": "열사병과 의식 저하가 온다.",
  },
  {
    "code": "C01",
    "type": "club",
    "suit": "♣",
    "name": "확률 마진",
    "en": "MARGIN CALL",
    "effect": "미리 선언한 사소하고 가능한 결과 하나의 확률을 조금 높인다.",
    "limit": "불가능한 결과는 만들 수 없고 반복할수록 반대 불운이 쌓인다.",
    "burst": "주변에서 연쇄적인 사소한 사고가 발생한다.",
  },
  {
    "code": "C02",
    "type": "club",
    "suit": "♣",
    "name": "표면 복제",
    "en": "SURFACE COPY",
    "effect": "접촉한 재료의 경도, 거칠기, 반사율을 작은 물체에 복제한다.",
    "limit": "형태와 내부 구조는 바뀌지 않으며 1분만 유지된다.",
    "burst": "피부가 복제 재질처럼 굳거나 갈라진다.",
  },
  {
    "code": "C03",
    "type": "club",
    "suit": "♣",
    "name": "조항 표식",
    "en": "CLAUSE MARK",
    "effect": "서로 동의한 짧은 약속을 기록해 고의로 어기면 통증을 준다.",
    "limit": "명확한 동의가 필요하며 절대 복종 조항은 성립하지 않는다.",
    "burst": "계약이 깨질 때 사용자도 일부 통증을 받는다.",
  },
  {
    "code": "C04",
    "type": "club",
    "suit": "♣",
    "name": "단거리 접힘",
    "en": "SHORT FOLD",
    "effect": "서로 보이는 두 문틀을 10미터 안에서 한 번 연결한다.",
    "limit": "양쪽이 열려 있고 시야에 있어야 하며 한 명 통과 후 닫힌다.",
    "burst": "구토와 방향 상실이 생긴다.",
  },
  {
    "code": "C05",
    "type": "club",
    "suit": "♣",
    "name": "하중 배분",
    "en": "LOAD SHARE",
    "effect": "두 비생명체 사이에서 무게를 재분배한다.",
    "limit": "총합 질량은 변하지 않고 두 대상은 12미터 이내여야 한다.",
    "burst": "사용자가 두 물체의 하중을 함께 느낀다.",
  },
  {
    "code": "C06",
    "type": "club",
    "suit": "♣",
    "name": "균열 명령",
    "en": "CRACK ORDER",
    "effect": "이미 존재하는 금이나 틈을 지정한 방향으로 성장시킨다.",
    "limit": "완전한 표면에는 쓸 수 없다.",
    "burst": "시질을 따라 피부가 갈라지고 출혈한다.",
  },
  {
    "code": "C07",
    "type": "club",
    "suit": "♣",
    "name": "귀환 표식",
    "en": "RETURN ADDRESS",
    "effect": "표식한 작은 물건 하나를 15미터 안에서 손으로 되돌려 부른다.",
    "limit": "강하게 붙잡히거나 고정된 물체는 오지 않는다.",
    "burst": "손가락 관절이 당겨지고 물건의 충격을 받는다.",
  },
  {
    "code": "C08",
    "type": "club",
    "suit": "♣",
    "name": "무음 구역",
    "en": "DEAD AIR",
    "effect": "반경 4미터 안에서 발생하는 소리를 크게 감쇠시킨다.",
    "limit": "완전한 무음이 아니며 외부 진동은 막지 못한다.",
    "burst": "해제 후 청각 과민과 통증이 생긴다.",
  },
  {
    "code": "C09",
    "type": "club",
    "suit": "♣",
    "name": "문턱 규칙",
    "en": "THRESHOLD RULE",
    "effect": "경계선에 단순 조건을 걸어 누가 무엇을 들고 통과했는지 감지한다.",
    "limit": "경계를 막지는 못하며 예·아니오로 판별 가능한 조건만 쓸 수 있다.",
    "burst": "실제 문과 가상의 경계를 혼동한다.",
  },
  {
    "code": "C10",
    "type": "club",
    "suit": "♣",
    "name": "카드 캐시",
    "en": "CARD CACHE",
    "effect": "카드나 칩에 손바닥 크기의 비생명체를 최대 세 개 보관한다.",
    "limit": "생명체와 폭발 중인 물체는 저장할 수 없다.",
    "burst": "손과 팔의 감각이 비어가는 느낌을 받는다.",
  },
  {
    "code": "C11",
    "type": "club",
    "suit": "♣",
    "name": "접착 명령",
    "en": "HARD BIND",
    "effect": "맞닿은 두 표면을 최대 30초간 강하게 붙인다.",
    "limit": "유분, 물, 모래가 많으면 약해진다.",
    "burst": "손가락이 서로 달라붙고 피부가 찢어진다.",
  },
  {
    "code": "C12",
    "type": "club",
    "suit": "♣",
    "name": "귀로 지정",
    "en": "RETURN VECTOR",
    "effect": "던지기 전 표식한 물체가 목표를 스친 뒤 사용자 쪽으로 돌아오게 한다.",
    "limit": "한 번에 하나, 20미터 이내에서만 작동한다.",
    "burst": "공간 인식이 꼬이고 돌아온 물체에 맞을 수 있다.",
  }
];
