window.SIX_SPIRITS_DATA = {
  imageBase: "https://i.cpvw.uk/6SC",
  factions: [
    {
      id: "six-spirits",
      group: "independent",
      name: "Six Spirits",
      ko: "식스 스피릿츠",
      tag: "INDEPENDENT DEALERS",
      symbol: "6",
      motto: "Proof is neutral. Its owners are not.",
      description: "프리몬트의 위스키 바 프루프를 거점으로 삼은 독립 딜러 여섯 명. 해마다 표적이 되지만, 하우스의 소유가 되는 대신 서로의 등을 맡긴다.",
      goal: "독립성과 프루프 생존",
      relation: "하우스·레드 채플의 우선 표적",
      featured: true
    },
    {
      id: "house",
      group: "authority",
      name: "The House",
      ko: "하우스",
      tag: "SYSTEM OWNER",
      symbol: "♛",
      motto: "House always wins.",
      description: "딜러 등록제, 억제제, 정보망과 캐시아웃 나이트를 장악한 카지노 권력. 보호와 편의를 제공하고 그 대가로 사람의 선택지를 소유한다.",
      goal: "딜러 생태계 완전 통제",
      relation: "정부와 결탁, 모든 세력의 채권자"
    },
    {
      id: "ledger",
      group: "authority",
      name: "The Ledger",
      ko: "더 렛저",
      tag: "HOUSE ENFORCEMENT",
      symbol: "§",
      motto: "Every debt is collectible.",
      description: "하우스 직속 집행국. 레이크 징수, 이탈자 회수, 랭킹 제재를 담당한다. 케일라의 전 직장이자 아드리엔의 옛 정보 라인",
      goal: "식스 스피릿츠 재흡수",
      relation: "케일라·아드리엔과 직접 충돌"
    },
    {
      id: "bda",
      group: "authority",
      name: "BDA",
      ko: "딜러관리국",
      tag: "FEDERAL BUREAU",
      symbol: "◉",
      motto: "Control through classification.",
      description: "정부 산하 딜러관리국. 이능력 통제와 징집권, 버스트 임계치 연구를 담당한다. 하우스와 결탁하지만 완전히 같은 편은 아니다.",
      goal: "고랭킹 딜러 전력화",
      relation: "사람을 보고서와 데이터로 분해"
    },
    {
      id: "red-chapel",
      group: "hostile",
      name: "Red Chapel",
      ko: "레드 채플",
      tag: "CULT DEALER CREW",
      symbol: "✟",
      motto: "Salvation needs an audience.",
      description: "스트립 남부의 고랭킹 딜러 크루. 살해, 공연, 종교적 쇼맨십을 결합하며 프루프를 매년 대표적인 제물로 지목한다.",
      goal: "프리몬트 영향권 장악",
      relation: "카시언이 물밑에서 세라핀을 지원"
    },
    {
      id: "uncut",
      group: "underground",
      name: "The Uncut",
      ko: "언컷",
      tag: "UNDERGROUND NETWORK",
      symbol: "◇",
      motto: "No registration. No ownership.",
      description: "미등록 시질 보유자와 마크가 모인 지하조직. 칩 밀수, 등록권 위조, 억제제 탈취를 통해 하우스의 독점을 흔들고자 노력하는 세력",
      goal: "등록제 붕괴와 생존권 확보",
      relation: "식스 스피릿츠와 이해관계 교차"
    }
  ],
  characters: [
    {
      id: "kayla",
      code: "A",
      group: "six-spirits",
      name: "Kayla Walker",
      thumbnail: "https://i.cpvw.uk/6SC/Kayla.png",
      ko: "케일라 워커",
      age: 34,
      origin: "미국 / 백인",
      role: "리더",
      callSign: "Buffalo Trace",
      suit: "♠",
      power: "중력 부여",
      rank: "PLATINUM",
      personality: "책임감 있는 ISTP 8w9. 침착하고 흔들림 없는 보호자. 위기에서는 동선·거리·무기 위치를 조용히 통제",
      history: "전직 그린베레에서 하우스 집행자로 옮겼다가 이탈했다. 과거 팀원을 잃은 경험 때문에 보호와 통제를 쉽게 구분하지 못함",
      style: "낡은 택티컬 스타일",
      detail: "군 시절 손목시계와 인식표. 오전 5시 기상, 장비 정렬 습관. 블랙커피와 스테이크, 버번(버팔로 트레이스) 선호",
      weapon: "Glock 19",
      quote: "Stay behind me, kid. <br> 내 뒤에 있어, 꼬맹아.",
      image: "00"
    },
    {
      id: "jackie",
      code: "C",
      group: "six-spirits",
      name: "Jackie Boone",
      thumbnail: "https://i.cpvw.uk/6SC/Jackie.png",
      ko: "재키 분",
      age: 34,
      origin: "미국 / 백인",
      role: "브리처",
      callSign: "Wild Turkey",
      suit: "♦",
      power: "폭발 에너지 주입",
      rank: "GOLD",
      personality: "장난기 많은 ESTP 7w8. 거리감이 없고 생각보다 몸이 먼저 움직임. 시끄럽고 거칠지만 팀에서 가장 빠르게 손을 내민다.",
      history: "길거리 파이터 출신. 손에 잡히는 것은 무엇이든 무기로 바꾸며, 쉬운 호의가 거의 없는 세계에서 드물게 먼저 믿어주는 사람",
      style: "바이커 펑크 스타일",
      detail: "낡은 지포 라이터와 너클 테이프. 늦잠, 즉흥, 도박. 정크푸드와 BBQ, 생맥주 선호",
      weapon: "손에 잡히는 건 아무거나",
      quote: "C'mon, trouble. Make it interesting. <br> 자, 사고뭉치. 한 판 벌려보자고.",
      image: "00"
    },
    {
      id: "elia",
      code: "B",
      group: "six-spirits",
      name: "Elia Mercer",
      thumbnail: "https://i.cpvw.uk/6SC/Elia.png",
      ko: "엘리아 머서",
      age: 32,
      origin: "미국 / 백인",
      role: "메딕",
      callSign: "Maker's Mark",
      suit: "♥",
      power: "생체 감응",
      rank: "SILVER",
      personality: "정중한 ISTJ 1w9. 습관적으로 배려하지만 위험 신호를 발견시 의료적 통제욕",
      history: "전직 외과의이자 블랙 클리닉 출신. 구하지 못한 친구의 죽음 이후, 늦기 전에 위험을 잡아야 한다는 강박 보유",
      style: "클리니컬 빈티지 스타일",
      detail: "휴대용 의료 키트와 체온계. 일지 작성, 도구 손질, 습관적 맥박 확인. 홍차와 수프 선호",
      weapon: "H&K P30",
      quote: "Your pulse is up. <br> 심박 올랐네요.",
      image: "00"
    },
    {
      id: "adrien",
      code: "D",
      group: "six-spirits",
      name: "Adrien Laurent",
      thumbnail: "https://i.cpvw.uk/6SC/Adrien.png",
      ko: "아드리엔 로랑",
      age: 29,
      origin: "프랑스계 / 백인",
      role: "전략가",
      callSign: "Grey Goose",
      suit: "♣",
      power: "확률 간섭",
      rank: "PLATINUM",
      personality: "냉정한 INTJ 3w4. 계산된 우아함과 귀족적 오만함, 감정을 결함으로 취급",
      history: "전직 하우스 정보부. 누구보다 하우스의 계산법을 잘 알며, 자신 역시 같은 방식으로 사람을 재단한다는 사실은 인정하지 않음",
      style: "럭셔리 모던 시크 스타일",
      detail: "확률 계산 노트와 은색 카드 케이스. 분 단위 일정. 에스프레소와 와인 선호",
      weapon: "치아파 라이노 권총",
      quote: "Statistically, chéri, this was avoidable. <br> 통계적으로 말이지, 자기야. 이건 피할 수 있었어.",
      image: "00"
    },
    {
      id: "maria",
      code: "E",
      group: "six-spirits",
      name: "Maria King",
      thumbnail: "https://i.cpvw.uk/6SC/Maria.png",
      ko: "마리아 킹",
      age: 27,
      origin: "미국 / 라티나",
      role: "침투·대외",
      callSign: "Cîroc",
      suit: "♥",
      power: "감정 주파수 조작",
      rank: "GOLD",
      personality: "발랄한 ESFP 3w2. 화려함과 플러팅을 갑옷처럼 두른 여자. 진심이 걸린 상대의 감정은 반칙이라며 읽지 않는다.",
      history: "전직 카지노 엔터테이너. 사랑받을 자격을 끊임없이 증명하려 하지만, 의미 없는 관계는 누구보다 단호하게 거절.",
      style: "라틴 글램 스타일",
      detail: "립글로스와 스마트폰. SNS, 거울, 음악을 반복 체크. 라틴 푸드와 칵테일 선호.",
      weapon: "금장 베레타",
      quote: "Relax, baby. I make panic look expensive. <br> 베이비, 진정해요. 난 패닉도 명품처럼 보이게 만들 수 있거든.",
      image: "00"
    },
    {
      id: "mikaela",
      code: "F",
      group: "six-spirits",
      name: "Mikaela Kowalski",
      thumbnail: "https://i.cpvw.uk/6SC/Mikaela.png",
      ko: "미케일라 코왈스키",
      age: 31,
      origin: "폴란드계 / 백인",
      role: "정찰·저격",
      callSign: "Belvedere",
      suit: "♠",
      power: "스나이핑",
      rank: "GOLD",
      personality: "조용한 INFJ 5w6. 관찰과 거리 두기로 자신을 지키며, 말보다 먼저 필요한 것을 준비하는 방식으로 헌신",
      history: "전직 정보 브로커. 폴란드어/러시아어/독일어/영어 사용. 그녀의 침묵은 정보가 없는 상태가 아니라 정보가 정리되는 시간",
      style: "모노톤 택티컬 스타일",
      detail: "폴란드 동전과 접이식 스코프. 체스, 독서, 네 개 언어 낱말 퀴즈. 치즈와 진한 차 선호",
      weapon: "Bor / VIS",
      quote: "Three exits. Two are watched. <br> 출구는 셋. 둘은 감시 중이야.",
      image: "00"
    },
    {
      id: "cassian",
      code: "H",
      group: "house",
      name: "Cassian Crow",
      thumbnail: "https://i.cpvw.uk/6SC/Cassian.png",
      ko: "카시언 크로우",
      age: 36,
      origin: "미국 / 백인",
      role: "하우스 총괄",
      callSign: "Banker",
      suit: "♥",
      power: "어웨이크닝",
      rank: "DIAMOND",
      personality: "ENTJ 8w9. 온화한 지배자이자 정중한 포식자. 웃을 때도 눈이 먼저 손익 계산",
      history: "카지노식 합리성으로 잔혹함을 비용 처리. 레드 채플의 세라핀은 그의 여동생이며, 드러내지 않은 채 물밑에서 지원",
      style: "쓰리피트 수트",
      detail: "플래티넘 블론드 슬릭백, 옅은 금안, 흰 면장갑. 시가는 습관이지만 언제나 들고 있지는 않음",
      weapon: "무기라니, 우아하지 못하군요. 제겐 하우스가 있습니다",
      quote: "I don't threaten. I clarify the odds. <br> 협박? 글쎄요, 가능성을 명확하게 보여주는 것 뿐입니다.",
      image: "00"
    },
    {
      id: "victor",
      code: "I",
      group: "house",
      name: "Victor Shane",
      thumbnail: "https://i.cpvw.uk/6SC/Victor.png",
      ko: "빅터 셰인",
      age: 45,
      origin: "미국 / 백인",
      role: "하우스 집행국장",
      callSign: "Executioner",
      suit: "♣",
      power: "계약 기반 언령",
      rank: "DIAMOND",
      personality: "ISTJ 1w9. 정중한 폭력과 계약 집착, 회수 본능. 협박을 제안처럼 말함",
      history: "케일라의 전 상관. 이탈을 배신보다 미정산 자산으로 여기며, 사람과 약속을 같은 장부에 기록",
      style: "맞춤 정장",
      detail: "금색 만년필, 카드 문양 넥타이, 소드 스틱. 흰 브릿지가 섞인 회갈색 올백과 적안.",
      weapon: "Sword cane(지팡이 검)",
      quote: "The House always wins. Eventually. <br> 하우스는 언제나 승리하지. 결국에는.",
      image: "00"
    },
    {
      id: "seraphine",
      code: "G",
      group: "red-chapel",
      name: "Seraphine Crow",
      thumbnail: "https://i.cpvw.uk/6SC/Seraphine.png",
      ko: "세라핀 크로우",
      age: 29,
      origin: "미국 / 백인",
      role: "레드 채플 리더",
      callSign: "Bloody Mary",
      suit: "♥",
      power: "광신 유도",
      rank: "PLATINUM",
      personality: "ENFJ 3w2. 관객 앞에서는 구원자, 무대 뒤에서는 도살자. 칭찬과 저주를 말하는 같은 목소리",
      history: "자신이 주님의 신부라고 믿으며 살해를 혼배성사로 연출. 하우스 총괄 카시언의 여동생",
      style: "주님을 위한 혼례복",
      detail: "찢어진 웨딩드레스, 플래티넘 블론드 장발. 장갑 없이 시질을 드러냄",
      weapon: "은색 가죽채찍",
      quote: "Come closer. Salvation hates an empty room. <br> 가까이 와요. 구원은 빈 자리를 싫어하거든.",
      image: "00"
    },
    {
      id: "luca",
      code: "J",
      group: "uncut",
      name: "Luca Hale",
      thumbnail: "https://i.cpvw.uk/6SC/Luca.png",
      ko: "루카 헤일",
      age: 24,
      origin: "미국 / 백인",
      role: "언컷 운반책",
      callSign: "Spark",
      suit: "♦",
      power: "열분해",
      rank: "UNREGISTERED",
      personality: "ISFP 6w7. 분노와 생존 본능, 인정 욕구 사이에서 흔들림. 딜러를 혐오하면서 동시에 딜러가 되고 싶어함.",
      history: "보증인이던 형이 캐시아웃 중 사망했고, 등록비가 될 칩은 킬러에게 강탈당했다. 시질은 있지만 등록하지 못한 경계층",
      style: "스트릿 택티컬 스타일",
      detail: "더티 블론드 숏컷, 초록 눈, 낡은 전술 장갑. 항상 도망갈 경로부터 확인",
      weapon: "잘 싸우진 않지만.. 필요하다면 능력을 사용해",
      quote: "Don't call me a mark. <br> 나한테 마크라고 하지 마.",
      image: "00"
    }
  ],
  tracks: [
    { title: "Neon After Midnight", artist: "링크 대기 / PLACEHOLDER", scene: "오프닝 / 프루프 바", duration: "03:42", url: "" },
    { title: "The Rake", artist: "링크 대기 / PLACEHOLDER", scene: "하우스 플로어", duration: "04:11", url: "" },
    { title: "Six Glasses, One Bullet", artist: "링크 대기 / PLACEHOLDER", scene: "팀 집결", duration: "03:18", url: "" },
    { title: "Red Chapel Procession", artist: "링크 대기 / PLACEHOLDER", scene: "세라핀 등장", duration: "05:02", url: "" },
    { title: "Fold State", artist: "링크 대기 / PLACEHOLDER", scene: "버스트 후폭풍", duration: "02:57", url: "" },
    { title: "Fremont at 05:51", artist: "링크 대기 / PLACEHOLDER", scene: "마지막 추격", duration: "04:36", url: "" }
  ],
  galleryScenes: [
    { code: "00", label: "명함", en: "Profile" },
    { code: "01", label: "미소", en: "Smile" },
    { code: "02", label: "짜증", en: "Annoyed" },
    { code: "03", label: "걱정", en: "Concern" },
    { code: "04", label: "경멸", en: "Contempt" },
    { code: "05", label: "분노", en: "Anger" },
    { code: "06", label: "슬픔", en: "Sadness" },
    { code: "07", label: "당황", en: "Flustered" },
    { code: "08", label: "사랑스러움", en: "Adorable" },
    { code: "09", label: "호기심", en: "Curious" },
    { code: "10", label: "흥미", en: "Interested" },
    { code: "11", label: "오열", en: "Sobbing" },
    { code: "12", label: "두려움", en: "Fear" },
    { code: "13", label: "피로", en: "Tired" },
    { code: "14", label: "부끄러움", en: "Embarrassed" },
    { code: "15", label: "폭소", en: "Laughter" },
    { code: "16", label: "전투", en: "Combat" },
    { code: "17", label: "이능력 전개", en: "Sigil Combat" },
    { code: "18", label: "패배", en: "Defeat" },
    { code: "19", label: "키스", en: "Kiss" },
    { code: "20", label: "결혼", en: "Wedding" },
    { code: "21", label: "유혹", en: "Temptation" },
    { code: "49", label: "키스조르기", en: "Begging for Kiss" },
    { code: "50", label: "음주", en: "Drunk" }
  ],
  gallery: [
    { code: "A", scene: "16", title: "Hold the Line", subtitle: "KAYLA / COMBAT" },
    { code: "G", scene: "17", title: "False Saint", subtitle: "SERAPHINE / SIGIL" },
    { code: "D", scene: "10", title: "Loaded Probability", subtitle: "ADRIEN / INTEREST" },
    { code: "C", scene: "16", title: "Anything Is a Weapon", subtitle: "JACKIE / COMBAT" },
    { code: "B", scene: "03", title: "Pulse Check", subtitle: "ELIA / CONCERN" },
    { code: "E", scene: "17", title: "Frequency Shift", subtitle: "MARIA / SIGIL" },
    { code: "F", scene: "16", title: "One Clean Angle", subtitle: "MIKAELA / COMBAT" },
    { code: "H", scene: "04", title: "The Banker Watches", subtitle: "CASSIAN / CONTEMPT" },
    { code: "I", scene: "10", title: "Terms and Conditions", subtitle: "VICTOR / INTEREST" }
  ]
};
